import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ICar } from '@interfaces/car';
import { CarType, Gearbox } from '@interfaces/enums';
import { IInsurance } from '@interfaces/insurance';

@Injectable({
  providedIn: 'root',
})
export class AnnouncementService {
  constructor() {}

  public list(): Observable<ICar[]> {
    return this.MOCList();
  }

  public MOCList(): Observable<ICar[]> {
    return of([
      {
        Id: '1',
        Price: 30,
        Model: 'Skoda Fabia',
        Type: CarType.Hatchback,
        Year: 2019,
        Fuel: 'Diesel',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'White',
        Pictures: [
          'https://localcarhires.com/media/thumbs/models/64/Skoda-Fabia-2020.jpg.352x190_q85_crop.jpg',
          'https://localcarhires.com/media/thumbs/cars/2021/05/1D5A8017-min.jpg.352x190_q85_crop.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Budva',
          Distance: 15,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
      {
        Id: '2',
        Price: 25,
        Model: 'Renault Clio 4',
        Type: CarType.Hatchback,
        Year: 2017,
        Fuel: 'Gasoline',
        Seats: 4,
        ChildrenBoosterSeats: 4,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'Black',
        Pictures: [
          'https://localcarhires.com/media/thumbs/models/663/Renault-Clio-Hb-Restyle-2016.jpeg.352x190_q85_crop.jpg',
          'https://localcarhires.com/media/thumbs/cars/2022/05/renta_car_-_ploce__1D5A70791651595469124.jpg.352x190_q85_crop.jpg',
          'https://localcarhires.com/media/thumbs/cars/2022/05/renta_car_-_ploce__1D5A70871651595469126.jpg.352x190_q85_crop.jpg',
          'https://localcarhires.com/media/thumbs/cars/2022/05/renta_car_-_ploce__1D5A70671651595469110.jpg.352x190_q85_crop.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Budva',
          Distance: 3,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '3',
        Price: 80,
        Model: 'VW Passat',
        Type: CarType.Sedan,
        Year: 2012,
        Fuel: 'Diesel',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: true,
        Color: 'Black',
        Pictures: [
          'http://blog.videgro.net/wp-content/uploads/2014/09/volkswagen_passat_b7_1.jpg',
          'https://www.chrome-auto.eu/wp-content/uploads/2017/10/vw-volkswagen-passat-b7-sedan-10-15-listwa-chrom-chromowana-3m-ochronna-na-klape-bagaznika-2.jpg',
        ],
        Gearbox: Gearbox.manual,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Kotor',
          Distance: 123,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '4',
        Price: 0,
        Model: 'Lada Niva',
        Type: CarType.SUV,
        Year: 2014,
        Fuel: 'Gasoline',
        Seats: 4,
        Pets: true,
        AC: false,
        Kids: false,
        Color: 'Black',
        Pictures: [
          'https://лада.онлайн/uploads/posts/2018-03/1520306848_logo.jpg',
          'https://лада.онлайн/uploads/posts/2017-02/1486443488_kuzov-2121.4.jpg',
        ],
        Gearbox: Gearbox.manual,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Podgorica',
          Distance: 2,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
      {
        Id: '5',
        Price: 5000,
        Model: 'Ferrari F40',
        Type: CarType.Coupe,
        Year: 1998,
        Fuel: 'Gasoline',
        Seats: 2,
        Pets: false,
        AC: false,
        Kids: false,
        Color: 'Red',
        Pictures: [
          'https://media.evo.co.uk/image/private/s--FDIc9h2---/v1584722625/evo/2020/03/Ferrari%20F40%20icon-14.jpg',
          'https://autoblog.rs/gallery/108/227082-ferrari%20f40%209.jpg',
        ],
        Gearbox: Gearbox.manual,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Russia',
          City: 'Barnaul',
          Distance: 1435,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
      {
        Id: '6',
        Price: 50,
        Model: 'Volkswagen Tiguan',
        Type: CarType.SUV,
        Year: 2010,
        Fuel: 'Diesel',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: true,
        Color: 'Brown',
        Pictures: [
          'https://www.vau-max.de/thumbs/img/News/39/25/00/p/p_full/schatz-ich-habe-unseren-touareg-geschrumpft-fahrbericht-vw-tiguan-2-0-tdi-170ps-mit-dem-suv-durch-europa-deutsche-autobahnen-oesterreichische-bergpaesse-und-kroatische-adriastrassen-im-schicken-kompakt-gelaendesportler-2539.jpg',
          'https://auto.ironhorse.ru/wp-content/uploads/2011/03/Tiguan-1-SS.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Spain',
          City: 'Barcelona',
          Distance: 405,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
      {
        Id: '7',
        Price: 10,
        Model: 'Daewoo Matiz',
        Type: CarType.Hatchback,
        Year: 2003,
        Fuel: 'Diesel',
        Seats: 3,
        Pets: true,
        AC: false,
        Kids: false,
        Color: 'Black',
        Pictures: [
          'https://s0.rbk.ru/v6_top_pics/media/img/7/69/754788612440697.jpeg',
          'https://avatars.mds.yandex.net/get-autoru-vos/2167656/7505405c29e8563e43824b1d8524ac85/456x342n',
        ],
        Gearbox: Gearbox.manual,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Uzbekistan',
          City: 'Tashkent',
          Distance: 1345,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
      {
        Id: '8',
        Price: 30,
        Model: 'Volkswagen Golf',
        Type: CarType.Hatchback,
        Year: 2020,
        Fuel: 'Diesel',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: true,
        Color: 'White',
        Pictures: [
          'https://vf.vin/static/uploads/images/sr2/vw/2022/07/27/vw-golf-2018-wvwzzzauzj8908670-img-1.jpg',
          'https://1.bp.blogspot.com/-AWA5z7KalcM/WfJf-MEM3cI/AAAAAAACiCY/f-oyov3UXHg3h5MTTTGayFz4PBv_lerxACLcBGAs/s640/volkswagen-golf-2018-uruguay-highline-gti-autoblog-precio%2B%25283%2529.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Serbian',
          City: 'Beograd',
          Distance: 290,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
      {
        Id: '9',
        Price: 50,
        Model: 'Suzuki Jimny',
        Type: CarType.SUV,
        Year: 2016,
        Fuel: 'Gasoline',
        Seats: 4,
        Pets: true,
        AC: true,
        Kids: true,
        Color: 'White',
        Pictures: [
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/048/116/original/IMG_0629.jpg?1642420592',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/048/118/original/IMG_0623.jpg?1642420605',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/048/121/original/IMG_0627.jpg?1642420625',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Serbian',
          City: 'Beograd',
          Distance: 290,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
      {
        Id: '10',
        Price: 60,
        Model: 'Peugeot 308 CC',
        Type: CarType.Cabriolet,
        Year: 2010,
        Fuel: 'Diesel',
        Seats: 4,
        Pets: true,
        AC: true,
        Kids: true,
        Color: 'Black',
        Pictures: [
          'https://www.terraecar.com/files/terrae-car-peugeot-308-2.jpg',
          'https://image1.mobiauto.com.br/images/api/images/v1.0/176177118/transform/fl_progressive,f_webp,w_300',
        ],
        Gearbox: Gearbox.manual,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Budva',
          Distance: 15,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '11',
        Price: 40,
        Model: 'Fiat 500c',
        Type: CarType.Cabriolet,
        Year: 2010,
        Fuel: 'Gasoline',
        Seats: 2,
        Pets: true,
        AC: true,
        Kids: true,
        Color: 'Yellow',
        Pictures: [
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/073/220/original/IMG-8ca0f34544d75d7150156585fcdc98b5-V.jpg?1666773344',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/073/217/original/IMG-72ad3aa959d1405a16906101dbd8e3e2-V.jpg?1666773342',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/073/219/original/IMG-c3517c773ac55c9531c464133c7e7649-V.jpg?1666773343',
        ],
        Gearbox: Gearbox.manual,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Becici',
          Distance: 20,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '12',
        Price: 100,
        Model: 'Mercedes-Benz GLA 200d',
        Type: CarType.Hatchback,
        Year: 2016,
        Fuel: 'Diesel',
        Seats: 4,
        Pets: true,
        AC: true,
        Kids: true,
        Color: 'Silver',
        Pictures: [
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/064/012/original/IMG_1914.JPG?1656951037',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/064/014/original/IMG_1919.JPG?1656951049',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/064/017/original/IMG_1917.JPG?1656951066',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Budva',
          Distance: 15,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '13',
        Price: 120,
        Model: 'Skoda Octavia',
        Type: CarType.Sedan,
        Year: 2015,
        Fuel: 'Diesel',
        Seats: 4,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'Brown',
        Pictures: [
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/008/190/original/IMG_20190602_071431.jpg?1574095616',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/039/548/original/1627587239817.jpg?1627587798',
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/039/549/original/1627587239828.jpg?1627587798',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Bar',
          Distance: 145,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '14',
        Price: 100,
        Model: 'Skoda SuperB',
        Type: CarType.Sedan,
        Year: 2018,
        Fuel: 'Diesel',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'Black',
        Pictures: [
          'https://s3-eu-west-1.amazonaws.com/localrent.images/images/files/000/059/656/original/IMG_20220514_171955.jpg?1653662481',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Zablac',
          Distance: 450,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '15',
        Price: 180,
        Model: 'Mercedes-Benz E 250',
        Type: CarType.Sedan,
        Year: 2013,
        Fuel: 'Diesel',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'Silver',
        Pictures: [
          'https://paultan.org/image/2013/08/Mercedes-W212-E-Class-FL-38-630x355.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Zablac',
          Distance: 300,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '16',
        Price: 60,
        Model: 'Toyota Prius',
        Type: CarType.Sedan,
        Year: 2020,
        Fuel: 'Hybrid',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'White',
        Pictures: [
          'https://www.toyota.com/imgix/content/dam/toyota/jellies/max/2022/prius/nightshadeeditionawd-e/1266/040/2.png?fm=webp&bg=white&w=768&h=328&q=90',
          'https://www.autobics.com/wp-content/uploads/2022/02/2022-Toyota-Prius-White-Rear-Quarter.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Podgorica',
          Distance: 80,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '17',
        Price: 90,
        Model: 'Honda Insight',
        Type: CarType.Sedan,
        Year: 2020,
        Fuel: 'Hybrid',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'Silver',
        Pictures: [
          'https://www.ccarprice.com/products/Honda-Insight-LX-2020.jpg',
          'https://images.hgmsites.net/med/2022-honda-insight-touring-cvt-angular-rear-exterior-view_100798318_m.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Niksic',
          Distance: 356,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '18',
        Price: 95,
        Model: 'Nissan Note',
        Type: CarType.Hatchback,
        Year: 2018,
        Fuel: 'Electro',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'White',
        Pictures: [
          'https://upload.wikimedia.org/wikipedia/commons/a/aa/Nissan_Note_%28E12%29_IMG_0338.jpg',
          'https://static.jutarnji.hr/images/slike/2022/05/01/24579081.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Kolashin',
          Distance: 300,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },

      {
        Id: '19',
        Price: 95,
        Model: 'Nissan Note',
        Type: CarType.Hatchback,
        Year: 2018,
        Fuel: 'Electro',
        Seats: 5,
        Pets: true,
        AC: true,
        Kids: false,
        Color: 'White',
        Pictures: [
          'https://upload.wikimedia.org/wikipedia/commons/a/aa/Nissan_Note_%28E12%29_IMG_0338.jpg',
          'https://static.jutarnji.hr/images/slike/2022/05/01/24579081.jpg',
        ],
        Gearbox: Gearbox.auto,
        Insurance: {} as IInsurance,
        Location: {
          Country: 'Montenegro',
          City: 'Kolashin',
          Distance: 300,
          Latitude: 42.2858721,
          Longitude: 18.8431396,
        },
      },
    ] as ICar[]);
  }
}
